import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { GoogleGenAI } from '@google/genai';
import { Loader2, TrendingUp, ChevronDown, ChevronUp } from 'lucide-react';

interface FitnessOverviewProps {
  userId: string;
  showGenerationCard?: boolean;
}

export default function FitnessOverview({ userId, showGenerationCard = true }: FitnessOverviewProps) {
  const [overview, setOverview] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [logs, setLogs] = useState<any[]>([]);
  const [expandedLogs, setExpandedLogs] = useState<Record<number, boolean>>({});

  useEffect(() => {
    fetchLogs();
  }, [userId]);

  const fetchLogs = async () => {
    try {
      const response = await fetch(`/api/fitness-overview/${userId}`);
      if (response.ok) {
        const data = await response.json();
        setLogs(data);
      }
    } catch (error) {
      console.error('Error fetching fitness overviews:', error);
    }
  };

  const toggleLog = (id: number) => {
    setExpandedLogs(prev => ({ ...prev, [id]: !prev[id] }));
  };

  const generateOverview = async () => {
    setLoading(true);
    try {
      const [metricsRes, nutritionRes, workoutsRes, logsRes] = await Promise.all([
        fetch(`/api/metrics/${userId}`),
        fetch(`/api/nutrition/${userId}`),
        fetch(`/api/workout-logs/${userId}`),
        fetch(`/api/body-composition/${userId}`)
      ]);

      const metrics = metricsRes.ok ? await metricsRes.json() : null;
      const nutrition = nutritionRes.ok ? await nutritionRes.json() : [];
      const workouts = workoutsRes.ok ? await workoutsRes.json() : [];
      const logs = logsRes.ok ? await logsRes.json() : [];

      const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY! });
      
      const metricsSummary = metrics ? `Weight: ${metrics.weight}kg, Body Fat: ${metrics.body_fat}%` : 'No metrics available';
      const nutritionSummary = nutrition.length > 0 ? `Recent average calories: ${Math.round(nutrition.reduce((acc: number, curr: any) => acc + curr.calories, 0) / nutrition.length)}` : 'No nutrition data';
      const workoutsSummary = workouts.slice(-10).map((w: any) => `${w.workout_id || 'Unknown'}`).join('; ');
      const analysisSummary = logs.slice(-3).map((l: any) => l.analysis.substring(0, 100)).join('; ');

      const prompt = `Analyze the user's fitness journey based on this summary:
      Metrics: ${metricsSummary}
      Nutrition: ${nutritionSummary}
      Workouts: ${workoutsSummary}
      Recent Body Composition Analysis Highlights: ${analysisSummary}

      Provide a concise, encouraging, and highly personalized overview of their progress. Highlight key trends, achievements, and areas for improvement. Keep the response under 500 words.`;

      const response = await ai.models.generateContent({
        model: 'gemini-3.1-pro-preview',
        contents: { parts: [{ text: prompt }] },
      });

      const newOverview = response.text || 'No overview available.';
      setOverview(newOverview);

      // Save to database
      await fetch(`/api/fitness-overview/${userId}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ overview: newOverview }),
      });
      fetchLogs();
    } catch (error) {
      console.error('Overview generation error:', error);
      setOverview('Error generating overview.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-8">
      {showGenerationCard && (
        <div className="bg-zinc-900/50 border border-white/10 rounded-3xl p-8 backdrop-blur-xl shadow-2xl">
          <h3 className="font-bold uppercase italic flex items-center gap-2 mb-2">
            <TrendingUp className="w-4 h-4 text-gold" />
            Fitness Journey Overview
          </h3>
          <p className="text-white/60 text-sm mb-8">
            This overview is generated by analyzing your body metrics, nutrition logs, workout history, and body composition data to provide personalized insights and trends.
          </p>
          <button 
            onClick={generateOverview}
            disabled={loading}
            className="w-full bg-zinc-800 text-white font-bold py-3 rounded-xl hover:bg-zinc-700 transition-colors flex items-center justify-center gap-2 mb-6"
            aria-label="Generate new fitness overview using AI"
          >
            {loading ? <Loader2 className="animate-spin" aria-hidden="true" /> : 'Generate Fitness Overview'}
          </button>
          {overview && (
            <div className="p-4 bg-white/5 rounded-xl border border-white/5">
              <p className="text-white/80 whitespace-pre-wrap text-sm">{overview}</p>
            </div>
          )}
        </div>
      )}

      {logs.length > 0 && (
        <div className="bg-zinc-900/50 border border-white/10 rounded-3xl p-8 backdrop-blur-xl shadow-2xl">
          <h3 className="font-bold uppercase italic mb-6">Overview History</h3>
          <div className="space-y-4">
            {logs.map((log) => (
              <div key={log.id} className="bg-white/5 rounded-xl border border-white/5 overflow-hidden">
                <button 
                  onClick={() => toggleLog(log.id)}
                  className="w-full p-4 flex items-center justify-between text-left"
                  aria-expanded={expandedLogs[log.id]}
                  aria-label={`Toggle overview from ${new Date(log.created_at).toLocaleString()}`}
                >
                  <div className="text-[10px] text-white/60">{new Date(log.created_at).toLocaleString()}</div>
                  {expandedLogs[log.id] ? <ChevronUp className="w-4 h-4 text-white/60" aria-hidden="true" /> : <ChevronDown className="w-4 h-4 text-white/60" aria-hidden="true" />}
                </button>
                <AnimatePresence>
                  {expandedLogs[log.id] && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      className="px-4 pb-4"
                    >
                      <p className="text-white/60 whitespace-pre-wrap text-sm">{log.overview}</p>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
